config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'

  devise_for :users,
              path: '',
              path_names: { sign_in: 'login', sign_out: 'logout', edit: 'profile' },
              controllers: { omniauth_callbacks: :omniauth_callbacks, registrations: 'registrations' }
  resources :users, only: :show
  resources :rooms do
    resource :reservations, only: :create
    resources :reviews, only: [:create, :destroy]
  end

  resources :conversations do
    resources :messages, only: [:create, :show, :index]
  end
  get '/preload', to: 'reservations#preload'
  get '/preview', to: 'reservations#preview'
  get '/reservations', to: 'reservations#index'
  get '/your_trips', to: 'reservations#your_trips'
  post '/notify', to: 'reservations#notify'
  post '/your_trips', to: 'reservations#your_trips'

  get '/search', to: 'pages#search'

  resources :photos
end

app/views/pages/home.html.erb
<%= form_tag search_path, method: :get do %>
  <div class="row">
    <div class="col-md-6">
      <%= text_field_tag :search, params[:search], placeholder: "Where are you going?", class: "form-control" %>
    </div>
    <div class="col-md-2">
      <%= text_field_tag :start_date, params[:start_date], placeholder: "Start Date", class: "form-control" %>
    </div>
    <div class="col-md-2">
      <%= text_field_tag :end_date, params[:end_date], placeholder: "End Date", class: "form-control" %>
    </div>
    <div class="col-md-2">
      <%= submit_tag "Search", class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

<br>

<div class="row text-center">
  <h2>Just for the weekend</h2>
  <p> Discover new, inspiring places close to home.</p>
</div>

<br>

<div class="row">
  <%= link_to "/search?utf8=✓&search=New+York&start_date=&end_date=&commit=Search" do %>
    <div class="col-md-4 col-sm-12">
      <div class="discovery-card" style="background-image: url(<%= image_path('New_York.jpg') %>)">
        <div class="va-container">
          <div class="va-middle text-center">
            <h2>
              <strong>New York</strong>
            </h2>
          </div>
        </div>
      </div>
    </div>
  <% end %>
  <%= link_to "/search?utf8=✓&search=London&start_date=&end_date=&commit=Search" do %>
    <div class="col-md-4 col-sm-12">
      <div class="discovery-card" style="background-image: url(<%= image_path('London.jpg') %>)">
        <div class="va-container">
          <div class="va-middle text-center">
            <h2>
              <strong>London</strong>
            </h2>
          </div>
        </div>
      </div>
    </div>
  <% end %>
  <%= link_to "/search?utf8=✓&search=Berlin&start_date=&end_date=&commit=Search" do %>
    <div class="col-md-4 col-sm-12">

      <div class="discovery-card" style="background-image: url(<%= image_path('Berlin.jpg') %>)">
        <div class="va-container">
          <div class="va-middle text-center">
            <h2>
              <strong>Berlin</strong>
            </h2>
          </div>
        </div>
      </div>

    </div>
  <% end %>

</div>

<br>

<div class="row text-center">
  <h2> Explore the world</h2>
  <p>See what people are travelling, all around the world</p>
</div>

<div class="row">
  <div class="col-md-12">
    <% @rooms.each do |room| %>
      <div class="col-md-4">
        <%= image_tag room_url(room, "medium") %>
        <br>
        <%= image_tag gravatar_for(room.user), class: "img-circle avatar-small" %>
        <%= link_to room_path(room) do %>
          <%= room.listing_name %>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/pages/search.html.erb
<div id="wrapper">

  <div id="sidebar">
    <script type="text/javascript" src="http://maps.googleapis.com/maps/api/js"></script>
    <div id="widget" class="sticky">
      <script type="text/javascript">
        function initialize() {
          var mapCanvas = document.getElementById("widget");
          <% if @arr_rooms.length > 0 %>
            var mapOptions = {
              center: new google.maps.LatLng(<%= @arr_rooms.first.latitude %>, <%= @arr_rooms.first.longitude %>),
              zoom: 10,
              mapTypeId: google.maps.MapTypeId.ROADMAP
            }
            var map = new google.maps.Map(mapCanvas, mapOptions)
            map.setZoom(10);
            <% @arr_rooms.each do |room| %>
              var marker = new google.maps.Marker({title: "<%= room.address %>", position: new google.maps.LatLng(<%= room.latitude %>, <%= room.longitude %>) });
              marker.setMap(map);
            <% end %>
          <% else %>
            var mapOptions = {
              center: new google.maps.LatLng(85, 100),
              zoom: 10,
              mapTypeId: google.maps.MapTypeId.ROADMAP
            }
            var map = new google.maps.Map(mapCanvas, mapOptions)
            map.setZoom(10);
          <% end %>

        }
        google.maps.event.addDomListener(window, "load", initialize);
      </script>

    </div>
  </div>

  <div id="article">

    <div class="row">
      <div class="col-md-12">
        <%= search_form_for @search, url: search_path do |f| %>

          <div class="row">

            <div class="col-md-12 spacer">
              <%= text_field_tag :search, params[:search], placeholder: "Where are you going?", class: "form-control" %>
            </div>

            <div class="col-md-3">
              <%= text_field_tag :start_date, params[:start_date], placeholder: "Start Date", class: "form-control" %>
            </div>
            <div class="col-md-3">
              <%= text_field_tag :end_date, params[:end_date], placeholder: "End Date", class: "form-control" %>
            </div>
            <div class="col-md-3">
              <%= f.text_field :price_gteq, placeholder: "Min Price", class: "form-control" %>
            </div>
            <div class="col-md-3">
              <%= f.text_field :price_lteq, placeholder: "Max Price", class: "form-control" %>
            </div>
          </div>

          <hr>

          <div class="row">
            <div class="col-md-4">
              <%= check_box_tag "q[room_type_eq_any][]", "Entire" %> Entire Room
            </div>
            <div class="col-md-4">
              <%= check_box_tag "q[room_type_eq_any][]", "Private" %> Private Room
            </div>
            <div class="col-md-4">
              <%= check_box_tag "q[room_type_eq_any][]", "Shared" %> Shared Room
            </div>
          </div>

          <hr>

          <div class="row">
            <div class="col-md-4">
              <div class="form-group">
                <label>Accommodate</label>
                <%= f.select :accommodate_gteq, [["1",1], ["2",2], ["3",3], ["4",4], ["5",5], ["6+",6]], prompt: "Select...", class: "form-control" %>
              </div>
            </div>

            <div class="col-md-4">
              <div class="form-group">
                <label>Bedrooms</label>
                <%= f.select :accommodate_gteq, [["1",1], ["2",2], ["3",3], ["4+",4]], prompt: "Select...", class: "form-control" %>
              </div>
            </div>

            <div class="col-md-4">
              <div class="form-group">
                <label>Bathrooms</label>
                <%= f.select :accommodate_gteq, [["1",1], ["2",2], ["3",3], ["4+",4]], prompt: "Select...", class: "form-control" %>
              </div>
            </div>
          </div>

          <hr>

          <div class="row">
            <div class="col-md-4">
              <%= check_box_tag "q[is_tv_eq]", true %> TV
            </div>
            <div class="col-md-4">
              <%= check_box_tag "q[is_kitchen_eq]", true %> Kitchen
            </div>
            <div class="col-md-4">
              <%= check_box_tag "q[is_internet_eq]", true %> Internet
            </div>
            <div class="col-md-4">
              <%= check_box_tag "q[is_heating_eq]", true %> Heating
            </div>
            <div class="col-md-4">
              <%= check_box_tag "q[is_air_eq]", true %> Air Conditioning
            </div>
          </div>

          <br>

          <div class="row">
            <%= f.submit "Search", class: "btn btn-primary" %>
          </div>

        <% end %>

        <hr>

        <div class="row">
          <% @arr_rooms.each do |room| %>
            <div class="col-md-4">
              <div class="panel panel-default">
                <div class="panel-heading preview">
                  <%= image_tag room.photos[0].image.url(:medium) if room.photos.length > 0 %>
                </div>
                <div class="panel-body">
                  <%= link_to room.listing_name, room %>
                </div>
              </div>
            </div>

          <% end %>
        </div>
      </div>


    </div>

  </div>

</div>

<script>
  $(function() {
    var stickyTop = $('.sticky').offset().top; // returns number

    $(window).scroll(function(){ // scroll event

      var windowTop = $(window).scrollTop(); // returns number

      if (stickyTop < windowTop) {
        $('.sticky').css({ position: 'fixed', top: 0 });
      }
      else {
        $('.sticky').css('position','static');
      }

    });
    $("#start_date").datepicker({
      dateFormat: 'dd-mm-yy',
      minDate: 0,
      readOnly: true,
      maxDate: '3m',
      onSelect: function(selected) {
        $('#end_date').datepicker("option", "minDate", selected);
        $('#end_date').attr('disabled', false);
      }
    });

    $("#end_date").datepicker({
      dateFormat: 'dd-mm-yy',
      minDate: 0,
      readOnly: true,
      maxDate: '3m',
      onSelect: function(selected) {
        $('#start_date').datepicker("option", "maxDate", selected);
      }
    });
  })
</script>