config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'

  devise_for :users,
              path: '',
              path_names: { sign_in: 'login', sign_out: 'logout', edit: 'profile' },
              controllers: { omniauth_callbacks: :omniauth_callbacks, registrations: 'registrations' }
  resources :users, only: :show
  resources :rooms do
    resource :reservations, only: :create
    resources :reviews, only: [:create, :destroy]
  end

  resources :conversations do
    resources :messages, only: [:create, :show, :index]
  end
  get '/preload', to: 'reservations#preload'
  get '/preview', to: 'reservations#preview'
  get '/reservations', to: 'reservations#index'
  get '/your_trips', to: 'reservations#your_trips'
  post '/notify', to: 'reservations#notify'
  post '/your_trips', to: 'reservations#your_trips'

  get '/search', to: 'pages#search'

  resources :photos
end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
  belongs_to :room
  belongs_to :user
  validate :start_date_must_be_earlier_than_end_date
  validates :start_date, presence: true
  validates :end_date, presence: true
  scope :in_between_range, -> (start_date, end_date) {where("? < start_date AND end_date < ?", start_date, end_date)}

  def start_date_must_be_earlier_than_end_date
    return if end_date.blank? || start_date.blank?
    errors.add(:end_date, "End date should greater than Start Date") if (end_date.to_date < start_date.to_date)
  end

  def self.room_booked_by_user?(room, user)
    where(user: user, room: room).present?
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :authenticate_user!, except: :notify

  def index
    @reservations = Reservation.where(room_id: current_user.rooms)
  end

  def preload
    room = Room.find(params[:room_id])
    today = Time.zone.today
    @reservations = room.reservations.where('start_date > ? OR end_date > ?', today, today)
    render json: @reservations
  end

  protect_from_forgery except: [:your_trips]

  def your_trips
    @reservations = current_user.reservations.where(status: true)
  end

  def create
    @reservation = current_user.reservations.create(reservation_params)
    if @reservation
      payment_info = {
        business: "ngdieulinh-facilitator@hotmail.com",
        cmd: "_xclick",
        upload: 1,
        notify_url: "http://airbnb-clone-mc.herokuapp.com/notify",
        amount: @reservation.total,
        item_name: @reservation.room.listing_name,
        item_number: @reservation.id,
        quantity: "1",
        return: "http://airbnb-clone-mc.herokuapp.com/your_trips"
      }
      redirect_to "https://www.sandbox.paypal.com/cgi-bin/webscr?" + payment_info.to_query
    else
      redirect_to @reservation.room, notice: "Oops, Something went wrong"
    end
  end

  protect_from_forgery except: [:notify]

  def notify
    params.permit!
    status = params[:payment_status]
    reservation = Reservation.find(params[:item_number])
    if status == "Completed"
      reservation.update_attributes status: true
    else
      reservation.destroy
    end
    render nothing: true
  end

  def preview
    start_date = Date.parse(params[:start_date])
    end_date = Date.parse(params[:end_date])
    @conflict = conflict?(start_date, end_date)
    render json: {conflict: @conflict}
  end

  private

  def conflict?(start_date, end_date)
    room = Room.find(params[:room_id])
    reservations = room.reservations.in_between_range(start_date, end_date)
    (reservations.size > 0 ? true : false)
  end

  def reservation_params
    params.require(:reservation).permit(:start_date, :end_date, :room_id, :price, :total)
  end
end

app/views/reservations/_form.html.erb
<%= form_for([@room, @room.reservations.new]) do |f| %>
  <div class="row">
    <div class="col-md-6">
      <label>Check In</label>
      <%= f.text_field :start_date, readonly: true, placeholder: "Start Date", class: "form-control" %>
    </div>

    <div class="col-md-6">
      <label>Check In</label>
      <%= f.text_field :end_date, readonly: true, placeholder: "End Date", class: "form-control" %>
    </div>

    <%= f.hidden_field :room_id, value: @room.id %>
    <%= f.hidden_field :price, value: @room.price %>
    <%= f.hidden_field :total, id: 'reservation_total' %>

    <div class="preview">
      <h4><span id="message"> Input Check-in & Check-out Date</span></h4>
      <table class="reservation-table" style="display:none;">
        <tbody>
          <tr>
            <td>Day(s)</td>
            <td><span id="reservation_days"></span></td>
          </tr>
           <tr>
            <td>Total</td>
            <td><span id="reservation_total_cost"></span></td>
          </tr>
        </tbody>
      </table>
      <br>
      <%= f.submit "Book Now", class: "btn btn-primary", id: 'btn_book' %>
    </div>
  </div>

<% end %>

<script type="text/javascript">
  function unavailable(date) {
    dmy = date.getDate() +'-' + (date.getMonth()+1) + '-' + date.getFullYear();
    return [$.inArray(dmy, unAvailableDates)==-1];
  }
  $(function(){
    unAvailableDates = [];
    $.ajax({
      dataType: 'json',
      url: '/preload',
      data: {
        'room_id':<%= @room.id %>
      },
      success: function(data){
        $.each(data, function(arr, obj){
          for(var d = new Date(obj.start_date); d<= new Date(obj.end_date); d.setDate(d.getDate() +1)){
            unAvailableDates.push($.datepicker.formatDate('d-m-yy', d));
          }
        });
      }
    });
    $('#reservation_start_date').datepicker({
      dateFormat: "dd-mm-yy",
      beforeShowDay: unavailable,
      onSelect: function(selectedDate) {
        $('#reservation_end_date').datepicker("option", "minDate", selectedDate);
      }
    });
    $('#reservation_end_date').datepicker({
      dateFormat: "dd-mm-yy",
      beforeShowDay: unavailable,
      onSelect: function(selectedDate){
        $('#reservation_start_date').datepicker("option", "maxDate", selectedDate);
        var start_date = $('#reservation_start_date').datepicker('getDate');
        var end_date = $(this).datepicker('getDate');
        var days = (end_date - start_date)/1000/60/60/24 + 1;
        var check_conflict_data = {
          'start_date': start_date,
          'end_date': end_date,
          'room_id': <%= @room.id %>
        };
        $.ajax({
          url: '/preview',
          dataType: 'json',
          data: check_conflict_data,
          success: function(data){
            if(data.conflict){
              $('#message').text('This date range is unavailable');
              $('.reservation-table').hide();
              $('#btn_book').attr('disabled', true);
            }else{
              $('#message').text('This date range is available');

              $('#btn_book').attr('disabled', false);
              var total = days * <%= @room.price %>;
              $('#reservation_days').text(days);
              $('#reservation_total_cost').text(total);
              $('#reservation_total').val(total);
              $('.reservation-table').show();
            }
          }
        });
      }
    });
  });

</script>

app/views/reservations/index.html.erb
<div class="row">
  <div class="col-md-3">
    <ul class="sidebar-list">
      <li class="sidebar-item">
        <%= link_to "Your listing", rooms_path %>
      </li>
      <li class="sidebar-item">
        <%= link_to "Your reservations", reservations_path %>
      </li>
      <li class="sidebar-item">
        <%= link_to "Your trips", your_trips_path %>
      </li>
    </ul>
  </div>
  <div class="col-md-9">

    <div class="panel panel-default">
      <div class="panel panel-heading">Listing</div>
      <div class="panel panel-body">
        <% @reservations.each do |reservation| %>
          <div class="row">
            <div class="col-md-2">
              <%= link_to room_path(reservation.room) do %>
                <%= image_tag reservation.room.photos.first.image.url(:thumb) if reservation.room.photos.length > 0 %>
              <% end %>
            </div>
            <div class="col-md-5">
              <h4><%= reservation.start_date.to_date %></h4>
            </div>
            <div class="col-md-5 right">
              <h4><%= reservation.end_date.to_date %></h4>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/reservations/your_trips.html.erb
<div class="row">
  <div class="col-md-3">
    <ul class="sidebar-list">
      <li class="sidebar-item">
        <%= link_to "Your listing", rooms_path %>
      </li>
      <li class="sidebar-item">
        <%= link_to "Your reservations", reservations_path %>
      </li>
      <li class="sidebar-item">
        <%= link_to "Your trips", your_trips_path %>
      </li>
    </ul>
  </div>
  <div class="col-md-9">
    <div class="panel panel-default">
      <div class="panel panel-heading">Listing</div>
      <div class="panel panel-body">
        <% @reservations.each do |reservation| %>
          <div class="row">
            <div class="col-md-3">
              <h4><%= reservation.start_date.strftime("%v") %></h4>
            </div>
            <div class="col-md-5">
              <%= link_to room_path(reservation.room) do %>
                <%= image_tag reservation.room.photos.first.image.url(:thumb) if reservation.room.photos.length > 0 %>
              <% end %>
            </div>
            <div class="col-md-2">
              <%= image_tag gravatar_for(reservation.room.user), class: "image-circle avatar-medium" %>
            </div>
            <div class="col-md-2 right">
              <h4>$<%= reservation.total %></h4>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>