config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'

  devise_for :users,
              path: '',
              path_names: { sign_in: 'login', sign_out: 'logout', edit: 'profile' },
              controllers: { omniauth_callbacks: :omniauth_callbacks, registrations: 'registrations' }
  resources :users, only: :show
  resources :rooms do
    resource :reservations, only: :create
    resources :reviews, only: [:create, :destroy]
  end

  resources :conversations do
    resources :messages, only: [:create, :show, :index]
  end
  get '/preload', to: 'reservations#preload'
  get '/preview', to: 'reservations#preview'
  get '/reservations', to: 'reservations#index'
  get '/your_trips', to: 'reservations#your_trips'
  post '/notify', to: 'reservations#notify'
  post '/your_trips', to: 'reservations#your_trips'

  get '/search', to: 'pages#search'

  resources :photos
end

app/models/room.rb
class Room < ActiveRecord::Base
  belongs_to :user
  has_many :photos
  has_many :reservations
  has_many :reviews

  geocoded_by :address

  after_validation :geocode, if: :address_changed?

  validates :home_type, presence: true
  validates :room_type, presence: true
  validates :accommodate, presence: true
  validates :bath_room, presence: true
  validates :bed_room, presence: true
  validates :listing_name, presence: true, length: {maximum: 100}
  validates :summary, presence: true, length: {maximum: 500}
  validates :address, presence: true

  scope :active, -> {where(active: true)}

  def average_rating
    reviews.count == 0 ? 0 : reviews.average(:star).round(2)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: [:edit, :show, :update]
  before_action :authenticate_user!, except: [:show]

  def index
    @rooms = current_user.rooms
  end

  def new
    @room = current_user.rooms.build
  end

  def show
    @photos = @room.photos
    @near_bys = @room.nearbys(10)
    @has_review = @room.reviews.find_by(user: current_user, room: @room).present? if current_user
    @booked = Reservation.room_booked_by_user?(@room, current_user) if current_user
    @reviews = @room.reviews
  end

  def create
    @room = current_user.rooms.build(room_params)
    if @room.save
      if params[:images]
        save_room_photos
      end
      redirect_to @room, notice: "Room created successfully"
    else
      render 'new'
    end
  end

  def edit
    @photos = @room.photos
    if current_user.id == @room.user.id
      render 'new'
    else
      redirect_to root_path, notice: "You don't have permission to edit this room"
    end
  end

  def update
    if @room.update(room_params)
      if params[:images]
        save_room_photos
      end
      redirect_to @room, notice: "Your room has been changed"
    else
      render 'new'
    end
  end

  private

    def save_room_photos
      params[:images].each do |image|
        @room.photos.create(image: image)
      end
    end

    def set_room
      @room = Room.find(params[:id])
    end

    def room_params
      params.require(:room).permit(:home_type, :room_type, :accommodate,
                                    :listing_name, :bed_room, :bath_room, :price,
                                    :summary, :address, :active,
                                    :is_tv, :is_kitchen, :is_air, :is_internet, :is_heating
                                  )
    end

end

app/views/rooms/_form.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    Create your beautiful place
  </div>
  <div class="panel-body">
    <div class="container">

      <%= form_for @room, html: {multipart: true} do |f| %>

        <div class="row">
          <div class="col-md-4 select">
            <div class="form-group">
              <label>Home Type</label>
              <%= f.select :home_type, [["Apartment","Apartment"], ["House","House"], ["Bed & Breakfast","Bed & Breakfast"]], id: "home_type", prompt: "Select...", class: "form-control" %>
            </div>
          </div>

          <div class="col-md-4 select">
            <div class="form-group">
              <label>Room Type</label>
              <%= f.select :room_type, [["Entire","Entire"], ["Private","Private"], ["Shared","Shared"]],prompt: "Select...", class: "form-control" %>
            </div>
          </div>

          <div class="col-md-4 select">
            <div class="form-group">
              <label>Accommodate</label>
              <%= f.select :accommodate, [["1",1], ["2",2], ["3",3], ["4",4], ["5",5], ["6+",6]], prompt: "Select...", class: "form-control" %>
            </div>
          </div>
        </div>

        <div class="row">
          <div class="col-md-4 select">
            <div class="form-group">
              <label>Bedrooms</label>
              <%= f.select :bed_room, [["1",1], ["2",2], ["3",3], ["4+",4]], prompt: "Select...", class: "form-control" %>
            </div>
          </div>

          <div class="col-md-4 select">
            <div class="form-group">
              <label>Bathrooms</label>
              <%= f.select :bath_room, [["1",1], ["2",2], ["3",3], ["4+",4]], prompt: "Select...", class: "form-control" %>
            </div>
          </div>
        </div>

        <div class="row">
          <div class="form-group">
            <label>Listing name</label>
            <%= f.text_field :listing_name, placeholder: "Be clear and descriptive", class: "form-control" %>
          </div>
        </div>

        <div class="row">
          <div class="form-group">
            <label>Summary</label>
            <%= f.text_area :summary, rows: 5, placeholder: "Tell about your house", class: "form-control" %>
          </div>
        </div>

        <div class="row">
          <div class="form-group">
            <label>Address</label>
            <%= f.text_field :address, placeholder: "What is your address?", class: "form-control" %>
          </div>
        </div>

        <div class="row">
          <div class="col-md-4">
            <div class="form-group">
              <%= f.check_box :is_tv %> TV
            </div>
            <div class="form-group">
              <%= f.check_box :is_kitchen %> Kitchen
            </div>
            <div class="form-group">
              <%= f.check_box :is_internet %> Internet
            </div>
          </div>

          <div class="col-md-4">
            <div class="form-group">
              <%= f.check_box :is_heating %> Heating
            </div>
            <div class="form-group">
              <%= f.check_box :is_air %> Air Conditioning
            </div>
          </div>
        </div>

        <div class="row">
          <div class="col-md-4">
            <div class="form-group">
              <label>Nightly Price</label>
              <div class="input-group">
                <div class="input-group-addon">$</div>
                <%= f.text_field :price, placeholder: "eg. $100", class: "form-group" %>
              </div>
            </div>
          </div>
        </div>

        <div class="row">
          <div class="col-md-4">
            <div class="form-group">
              <span class="btn btn-default btn-file">
                <i fa fa-cloud-upload fa-lg> Upload photos
                <%= file_field_tag 'images[]', type: :file, multiple: true %>
              </span>
            </div>
          </div>
        </div>

        <div class="row">
          <div id="photos">
            <%= render 'photos/list' %>
          </div>
        </div>

        <div class="row">
          <div class="form-group">
            <%= f.check_box :active %> Active
          </div>
        </div>

        <div class="actions">
          <%= f.submit "Save", class: "btn btn-primary" %>
        </div>

      <% end %>

    </div>
  </div>
</div>

app/views/rooms/index.html.erb
<div class="row">
  <div class="col-md-3">
    <ul class="sidebar-list">
      <li class="sidebar-item">
        <%= link_to "Your listing", rooms_path %>
      </li>
      <li class="sidebar-item">
        <%= link_to "Your reservations", reservations_path %>
      </li>
      <li class="sidebar-item">
        <%= link_to "Your trips", your_trips_path %>
      </li>
    </ul>
  </div>
  <div class="col-md-9">
    <div class="panel panel-default">
      <div class="panel panel-heading">Listing</div>
      <div class="panel panel-body">
        <% @rooms.each do |room| %>
          <div class="row">
            <div class="col-md-2">
              <%= image_tag room.photos.first.image.url(:thumb) if room.photos.length > 0 %>
            </div>
            <div class="col-md-7">
              <h4><%= room.listing_name %></h4>
            </div>
            <div class="col-md-3 right">
              <%= link_to "Update", edit_room_path(room), class: "btn btn-primary" %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/rooms/new.html.erb
<%= render 'form' %>

app/views/rooms/show.html.erb
<%= javascript_include_tag '//maps.googleapis.com/maps/api/js' %>
<div class="panel panel-default">
  <div class="panel-body">

    <!-- Image -->
    <div class="row">
      <div class="col-md-12">
        <%= image_tag @photos[0].image.url(), class: "img-responsive" if @photos.length > 0 %>
      </div>
    </div>

    <br>

    <!-- Main Info -->
    <div class="row">
      <div class="col-md-8">
        <div class="row">
          <div class="col-md-3 text-center">
            <%= image_tag gravatar_for(@room.user), class: "img-circle avatar-large" %><br><br>
            <%= @room.user.fullname %>
          </div>

          <div class="col-md-9">
            <h4><%= @room.listing_name %></h4>
            <%= @room.address %>

            <div class="row text-center row-space-1">
              <div class="col-sm-3">
                <i class="fa fa-home fa-2x"></i>
              </div>
              <div class="col-sm-3">
                <i class="fa fa-users fa-2x"></i>
              </div>
              <div class="col-sm-3">
                <i class="fa fa-bed fa-2x"></i>
              </div>
              <div class="col-sm-3">
                <i class="fa fa-ship fa-2x"></i>
              </div>
            </div>

            <div class="row text-center">
              <div class="col-sm-3">
                <%= @room.home_type %>
              </div>
              <div class="col-sm-3">
                <%= @room.accommodate %> <%= @room.accommodate > 1? "Guests" : "Guest" %>
              </div>
              <div class="col-sm-3">
                <%= @room.bed_room %> <%= @room.bed_room > 1? "Bedrooms" : "Bedroom" %>
              </div>
              <div class="col-sm-3">
                <%= @room.bath_room %> <%= @room.bath_room > 1? "Bathrooms" : "Bathroom" %>
              </div>
            </div>

          </div>
        </div>
      </div>

      <div class="col-md-4">
        <!-- Reservation form -->
        <%= render "reservations/form" %>
      </div>
    </div>

    <!-- About -->
    <div class="row">
      <div class="col-md-12">
        <h2>About This Listing</h2>
        <p><%= @room.summary %></p>
      </div>
    </div>

    <!-- Amenities -->
    <div class="row">
      <div class="col-md-2">
        <p>Amentities</p>
      </div>
      <div class="col-md-10">
        <div class="row">
          <div class="col-md-6">
            <ul class="amenities">
              <li class="<%= 'text-line-through' if !@room.is_tv %>">TV</li>
              <li class="<%= 'text-line-through' if !@room.is_kitchen %>">Kitchen</li>
              <li class="<%= 'text-line-through' if !@room.is_internet %>">Internet</li>
            </ul>
          </div>
          <div class="col-md-6">
            <li class="<%= 'text-line-through' if !@room.is_heating %>">Heating</li>
            <li class="<%= 'text-line-through' if !@room.is_air %>">Air Conditioning</li>
          </div>
        </div>
      </div>
    </div>

    <!-- Carousel -->
    <div class="row">
      <div class="col-md-10 col-md-offset-1">
        <div id="myCarousel" class="carousel slide" data-ride="carousel">

          <% if @photos %>
            <!-- Indicators -->
            <ol class="carousel-indicators">
              <% @photos.each do |photo| %>
                <li data-target="#myCarousel" data-slide-to="<%= photo.id %>"></li>
              <% end %>
            </ol>
          <% end %>

          <div class="carousel-inner" role="listbox">
            <% if @photos %>
              <% @photos.each do |photo| %>
                <div class="item <%= 'active' if photo.id == @photos[0].id %>">
                  <%= image_tag photo.image.url() %>
                </div>
              <% end %>
            <% end %>
          </div>

          <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
          </a>
        </div>
      </div>
    </div>

    <!-- Reviews -->
    <div class="row">
      <%= render "reviews/list" %>
      <div class="col-md-12">
        <% if current_user && @booked && !@has_review %>
          <%= render "reviews/form" %>
        <% end %>
      </div>
    </div>

    <!-- Map -->
    <div class="row">
      <div class="col-md-10 col-md-offset-1">
        <div id="map"></div>
        <script type="text/javascript">
          function initialize() {
            var mapCanvas = document.getElementById('map');
            var mapOptions = {
              center: new google.maps.LatLng(<%= @room.latitude %>, <%= @room.longitude %>),
              zoom: 10,
              mapTypeId: google.maps.MapTypeId.ROADMAP
            }
            var map = new google.maps.Map(mapCanvas, mapOptions)
            map.setZoom(10);
            var marker = new google.maps.Marker({title: '<%= @room.address %>', position: new google.maps.LatLng(<%= @room.latitude %>, <%= @room.longitude %>) });
            marker.setMap(map);
          }
          google.maps.event.addDomListener(window, 'load', initialize);
        </script>
      </div>
    </div>


    <!-- Close by rooms -->
    <div class="row">
      <div class="col-md-10 col-md-offset-1">

        <% if @near_bys %>
          <% for room in @near_bys do %>
            <div class="col-md-4">
              <div class="panel panel-default">
                <div class="panel-heading">
                  <% if room.photos.present? %>
                    <%= image_tag room.photos.first.image.url(:medium) %>
                  <% else %>
                    <%= image_tag('sample-room.jpg') %>
                  <% end %>
                </div>
                <div class="panel-body">
                  <%= link_to room.listing_name, room %><br>
                  (<%= room.distance.round(2) %> smiles away)
                </div>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>


  </div>
</div>